require_relative 'download_apple_push_notification_certificate_signing_request_response'
module MicrosoftGraph::DeviceManagement::ApplePushNotificationCertificate::MicrosoftGraphDownloadApplePushNotificationCertificateSigningRequest
end
