require_relative 'does_user_have_accessuser_id_user_id_tenant_id_tenant_id_user_principal_name_user_principal_name_response'
module MicrosoftGraph::Me::JoinedTeams::Item::PrimaryChannel::DoesUserHaveAccessuserIdUserIdTenantIdTenantIdUserPrincipalNameUserPrincipalName
end
