module MicrosoftGraph
    module Models
        SecurityDetectionSource = {
            Unknown: :Unknown,
            MicrosoftDefenderForEndpoint: :MicrosoftDefenderForEndpoint,
            Antivirus: :Antivirus,
            SmartScreen: :SmartScreen,
            CustomTi: :CustomTi,
            MicrosoftDefenderForOffice365: :MicrosoftDefenderForOffice365,
            AutomatedInvestigation: :AutomatedInvestigation,
            MicrosoftThreatExperts: :MicrosoftThreatExperts,
            CustomDetection: :CustomDetection,
            MicrosoftDefenderForIdentity: :MicrosoftDefenderForIdentity,
            CloudAppSecurity: :CloudAppSecurity,
            Microsoft365Defender: :Microsoft365Defender,
            AzureAdIdentityProtection: :AzureAdIdentityProtection,
            Manual: :Manual,
            MicrosoftDataLossPrevention: :MicrosoftDataLossPrevention,
            AppGovernancePolicy: :AppGovernancePolicy,
            AppGovernanceDetection: :AppGovernanceDetection,
            UnknownFutureValue: :UnknownFutureValue,
            MicrosoftDefenderForCloud: :MicrosoftDefenderForCloud,
            MicrosoftDefenderForIoT: :MicrosoftDefenderForIoT,
            MicrosoftDefenderForServers: :MicrosoftDefenderForServers,
            MicrosoftDefenderForStorage: :MicrosoftDefenderForStorage,
            MicrosoftDefenderForDNS: :MicrosoftDefenderForDNS,
            MicrosoftDefenderForDatabases: :MicrosoftDefenderForDatabases,
            MicrosoftDefenderForContainers: :MicrosoftDefenderForContainers,
            MicrosoftDefenderForNetwork: :MicrosoftDefenderForNetwork,
            MicrosoftDefenderForAppService: :MicrosoftDefenderForAppService,
            MicrosoftDefenderForKeyVault: :MicrosoftDefenderForKeyVault,
            MicrosoftDefenderForResourceManager: :MicrosoftDefenderForResourceManager,
            MicrosoftDefenderForApiManagement: :MicrosoftDefenderForApiManagement,
            NrtAlerts: :NrtAlerts,
            ScheduledAlerts: :ScheduledAlerts,
            MicrosoftDefenderThreatIntelligenceAnalytics: :MicrosoftDefenderThreatIntelligenceAnalytics,
            BuiltInMl: :BuiltInMl,
            MicrosoftInsiderRiskManagement: :MicrosoftInsiderRiskManagement,
            MicrosoftSentinel: :MicrosoftSentinel,
        }
    end
end
