require_relative 'get_pstn_calls_with_from_date_time_with_to_date_time_response'
module MicrosoftGraph::Communications::CallRecords::MicrosoftGraphCallRecordsGetPstnCallsWithFromDateTimeWithToDateTime
end
