require_relative 'get_applicable_policy_requirements_response'
module MicrosoftGraph::IdentityGovernance::EntitlementManagement::Catalogs::Item::AccessPackages::Item::MicrosoftGraphGetApplicablePolicyRequirements
end
