require_relative 'get_applicable_policy_requirements_response'
module MicrosoftGraph::IdentityGovernance::EntitlementManagement::AccessPackages::Item::MicrosoftGraphGetApplicablePolicyRequirements
end
