require_relative 'get_available_extension_properties_response'
require_relative 'get_available_extension_properties_post_request_body'
module MicrosoftGraph::Contracts::GetAvailableExtensionProperties
end
